---
name: "Nicholas Baetge"
position: "PhD Candidate"
address: "UC Santa Barbara, IGP-Marine Science"
phone: +1 310-944-4660
www: nbaetge.github.io
email: nicholasbaetge@gmail.com
twitter: nbaetge91
github: nbaetge
aboutme: ""
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::moderncv:
    theme: casual

---

```{r eval=FALSE, include=FALSE}
# Remember to spell check!!
data_files <- list.files(here("data"), pattern = ".csv", full.names = TRUE)
spelling::spell_check_files(c("CV.Rmd", data_files))
```

```{r eval=FALSE, include=FALSE}
#To update CV on my website, run the following code in the console:
rmarkdown::render("CV.Rmd", output_file = "~/GITHUB/nbaetge.github.io/vitae")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(lubridate)
library(here)
library(readxl)
library(glue)
library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("here", "here")
```

```{r experience, inclue=FALSE}
jobs.raw <- read_csv(here::here("data", "jobs.csv"))
jobs <-
  jobs.raw %>% 
  fill(Start, End, What,  Where, Tag) %>%  
  mutate(Start = mdy(Start),
         End = mdy(End)) %>% 
  mutate(When = case_when(
    is.na(End) ~ glue("{year(Start)}--Present") %>% as.character(),
    year(Start) == year(End) ~ year(End) %>% as.character(),
    TRUE ~ glue("{year(Start)}--{year(End)}") %>% as.character()
  )) %>% 
  mutate(End = if_else(is.na(End), today() + years(2), End)) #if no end date specified, set it to two years from now for sorting purposes, i.e. so jobs I'm still doing show up at top.
```

```{r presentations, include=FALSE}
presentations.raw <- read_csv(here("data", "presentations.csv"))
presentations <- 
  presentations.raw %>% 
  mutate(When = mdy(When)) %>% 
  filter(When < today()) #exclude upcoming talks 

```

```{r prof-devel, include=FALSE}
development.raw <- read_csv(here("data", "professional development.csv"))
development <- 
  development.raw %>% 
  mutate(Start = mdy(start),
         End = mdy(end)) %>% 
  mutate(When = case_when(
    is.na(End) ~ glue("{year(Start)}--Present") %>% as.character(),
    year(Start) == year(End) ~ year(End) %>% as.character(),
    TRUE ~ glue("{year(Start)}--{year(End)}") %>% as.character()
  ))
```

```{r awards, include=FALSE}
awards.raw <- read_csv(here("data", "awards and grants.csv"))
awards <- awards.raw %>% 
  arrange(desc(date))
```

```{r edu, include=FALSE}
edu.raw <- read_csv(here("data", "education.csv"))
edu <-
  edu.raw %>% 
  mutate(pi = if_else(!is.na(pi), glue("PI: {pi}"), as.character(NA)),
         dissertation = glue("\\textbf{[dissertation]}", .open = "[", .close = "]")) %>% 
  gather(dissertation, pi, key = "whytype", value = "why")
edu["why"]
```

```{r outreach, include=FALSE}

fieldwork.raw <- read_csv(here("data", "fieldwork.csv"))
fieldwork <- fieldwork.raw %>% 
  mutate(When = mdy(When),
         When = year(When))
```


# Education 

```{r }
detailed_entries(edu, 
                 when = glue("{start_date}--{end_date}"),
                 what = degree,
                 where = university,
                 with = department,
                 why = why,
                 .protect = FALSE)

```




# Grants

```{r}
awards %>%
  filter(tag == "grant") %>%
  detailed_entries(what = award, when = date, with = with, why = amount)
```

# Awards and Honors

```{r}
 awards %>% 
  filter(!tag %in% c("failed", "travel", "grant")) %>% 
  brief_entries(what = award, when = date, with = with)
```

# Publications

<!-- ^\*^ indicates undergraduate mentee author   -->

```{r publications}

scholar::get_publications("Ca8wN7sAAAAJ", flush = TRUE) %>% 
  mutate_at(vars(year), as.character) %>% 
  #in prep/review
  dplyr::add_row(
    title = "Seasonal Regulation and Fate of Dissolved Organic Carbon Accumulation in the Northwest Atlantic",
    author = "Baetge, N., Carlson, C., et al",
    journal = "",
    number = " ",
    cites = 0,
    year = "in prep",
    cid = NA,
    pubid = NA
    ) %>%
   add_row(
    title = "Seasonality of the microbial community composition in the western North Atlantic",
    author = "Bolaños, L., Choi, C.J., Worden, A., Baetge, N., Carlson, C., Giovannoni, S",
    journal = "Frontiers",
    number = "",
    cites = 0,
    year = "in review",
    cid = NA,
    pubid = NA
  ) %>%
  add_row(
    title = "Seasonal mixed layer dynamics shape phytoplankton physiology, viral infection, and accumulation in the North Atlantic",
    author = "Diaz, B., Knowles, B., Johns, C., Laber, C., Bondoc, K.G.V, Harvey, E., Lowenstein, D., Fredricks, H., Haramaty, L., Natale, F., Graff, J., Westberry, T., Haentjens, N., Baetge, N., Mojica, K., Gaube, P., Boss, E., Carlson, C., Behrenfeld, M., Van Mooy, B., and Bidle, K",
    journal = "Nature Communications",
    number = "",
    cites = 0,
    year = "in review",
    cid = NA,
    pubid = NA
  ) %>%
  add_row(
    title = "Role of Sea Surface Microlayer Properties in Cloud Formation",
    author = "Hendrickson, B., Brooks, S., Thornton, D., Moore, R., Crosbie, E., Ziemba, L., Carlson, C., Baetge, N., Mirrielees, J., and Alsante, A",
    journal = "Frontiers",
    number = "",
    cites = 0,
    year = "in review",
    cid = NA,
    pubid = NA
  ) %>%
  arrange(desc(year)) %>%
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = paste(journal, number, sep = ". ")
  )
 #bibliography_entries(file = "~/GITHUB/curriculum-vitae/data/MyPublications.bib", title = NULL)
```




# Presentations

## Research Talks

```{r}
presentations %>% 
  filter(Tag %in% c("talk", "invited")) %>% 
  arrange(desc(When)) %>% 
  detailed_entries(what = Title,
                   when = glue("{month(When, label = TRUE)} {year(When)}"),
                   with = Conference,
                   where = Location,
                   why = Award,
                   .protect = FALSE)
```

## Posters

```{r}
presentations %>% 
  filter(Tag == "poster") %>% 
  arrange(desc(When)) %>% 
  detailed_entries(what = Title,
                   when = glue("{month(When, label = TRUE)} {year(When)}"),
                   with = Conference,
                   where = Location,
                   why = Award,
                   .protect = FALSE)
```

# Teaching Experience

```{r}
jobs %>%
  filter(Tag == "teaching", year(Start) > 2005) %>%
  arrange(desc(Start)) %>% 
  detailed_entries(
    what = What,
    when = When,
    where = Where,
    .protect = FALSE
  )
```

## Mentorship

```{r}
jobs %>%
  filter(Tag == "mentorship", year(Start) > 2005) %>%
  arrange(desc(Start)) %>% 
  detailed_entries(
    what = What,
    when = When,
    where = Where,
    .protect = FALSE
  )
```


# Cruise Experience

```{r}
fieldwork %>%
  arrange(desc(When)) %>%
  detailed_entries(when = When,
                   what = What,
                   with = With,
                   where = Days)
```

# Service

```{r}
jobs %>%
  filter(Tag == "service") %>% 
  arrange(desc(When)) %>%
  detailed_entries(
    what = What,
    when = When,
    where = Where
  )
```

**Manuscript Reviews**

- Science Advances (1)
- Aquatic Microbial Ecology (1)
- ISME (1)

# Professional Development

```{r}
development %>% 
  brief_entries(
    what = title,
    when = When,
    with = location
  )
```

\pagebreak